POST http://localhost:3000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmlvIiwiaWF0IjoxNzIwNzAzNDkxfQ.FmsDrL5AeoruQI7lnAOnvqCHRDaUJDR6Slu-ksLfY7s"
}

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "nio",
    "password": "123"
}

###

POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "nio",
    "password": "123"
}

###
POST http://localhost:3000/task HTTP/1.1
content-type: application/json

{
  "username": "nio",
  "taskbody": "Task 2 body",
  "tasktime": "20-09-24"
}
###
@username = nio
GET http://localhost:3000/tasks/{{username}} 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmlvIiwiaWF0IjoxNzIwOTU1MjE2fQ.pIILzylFQxtnwWJLylOYeh4P7dLQk6CUoiaEusaUs6w

###
@username = "nio"
@taskid = 1
DELETE http://localhost:3000/task/:username/:taskid HTTP/1.1




